# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('registrationDate', models.DateTimeField(blank=True, db_column='registrationDate', null=True)),
                ('dateOfPayment', models.DateTimeField(blank=True, db_column='dateOfPayment', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='amount', null=True)),
                ('description', models.TextField(blank=True, db_column='description', help_text='e.g. tudom is en', null=True, verbose_name='Description vagy mi')),
                ('category', models.CharField(blank=True, db_column='category', help_text='e.g. tudom is en megint mi', max_length=35, null=True, verbose_name='Kategória vagy mi')),
            ],
            options={
                'db_table': 'incomes',
                'managed': False,
            },
        ),
    ]
